baseURL = "https://mickeymiao7.github.io"
languageCode = "en-us"
title = "Mickey Blog"
theme = "ananke"

[params]
  header_image = "images/cover.jpg"
  SEOTitle = "Mickey's Blog | Mickey 的博客"

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
