baseURL = "https://mickeymiao7.github.io"
languageCode = "en-us"
title = "Mickey Blog"
theme = "PaperMod"

[params]
  header_image = "images/cover.jpg"
  SEOTitle = "Mickey's Blog | Mickey 的博客"

  [params.homeInfoParams]
    Title = "Mickey Blog"
    Content = '''996 程序员，007 白日梦妄想家'''

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/MickeyMiao7"

  [[params.socialIcons]]
    name = "rss"
    url = "index.xml"

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
